"""initial migration

Revision ID: 938d47ddd45c
Revises: 
Create Date: 2025-12-28 09:45:25.730690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938d47ddd45c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email пользователя (уникальный)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Полное имя пользователя'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='Таблица авторизованных пользователей'
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('generation_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='ID пользователя (NULL для анонимных запросов)'),
    sa.Column('request_type', sa.String(length=100), nullable=False, comment='Тип генерации (job_description, resume_evaluation, etc.)'),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Входные данные запроса'),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Результат генерации'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус выполнения (success, error, timeout)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Время выполнения в миллисекундах'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица результатов генераций LLM/ML воркеров'
    )
    op.create_index('ix_generation_results_created_at', 'generation_results', ['created_at'], unique=False)
    op.create_index('ix_generation_results_request_type', 'generation_results', ['request_type'], unique=False)
    op.create_index('ix_generation_results_status', 'generation_results', ['status'], unique=False)
    op.create_index('ix_generation_results_user_id', 'generation_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generation_results_user_id', table_name='generation_results')
    op.drop_index('ix_generation_results_status', table_name='generation_results')
    op.drop_index('ix_generation_results_request_type', table_name='generation_results')
    op.drop_index('ix_generation_results_created_at', table_name='generation_results')
    op.drop_table('generation_results')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
